src/warbler/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from app_warbler import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.ListAllTweetsView.as_view(), name='list-all-tweets'),
    path('create_tweet/', views.CreateTweetView.as_view(), name='create-tweet'),
    path('login/', auth_views.LoginView.as_view(template_name='app_warbler/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='app_warbler/logout.html'), name='logout'),
    path('tweet_details/<int:pk>/', views.TweetDetailsView.as_view(), name='tweet-details'),
    path('update_tweet/<int:pk>/', views.UpdateTweetView.as_view(), name='update-tweet'),
    path('profile_details/<int:pk>/', views.ProfileDetailsView.as_view(), name='profile-details'),
    path('create_user/', views.CreateUserView.as_view(), name='create-user-sign-in'),
    path('create_message/<int:to_user>/', views.CreateMessageView.as_view(), name='create-message'),
    path('user_messages/<int:pk>/', views.ListUserMessagesView.as_view(), name='user-messages'),
    path('message_details/<int:pk>/', views.MessageDetailsView.as_view(), name='msg-details'),
    path('delete_user/<int:pk>/', views.DeleteUserView.as_view(), name='delete-user'),
    path('update_user/<int:pk>/', views.UpdateUserAndProfileView.as_view(), name='update-user'),
    path('delete_tweet/<int:pk>/', views.DeleteTweetView.as_view(), name='delete-tweet'),
    path('delete_comment/<int:pk>/', views.DeleteCommentView.as_view(), name='delete-comment'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='app_warbler/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app_warbler/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='app_warbler/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='app_warbler/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app_warbler/models.py
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='Deleted user')[0]


class Profile(models.Model):
    user         = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    photo        = models.ImageField(default='default_user.jpg', upload_to='profile_pics', )
    about_myself = models.TextField(max_length=256, null=True, blank=True)
    is_blocked   = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username}\' profile'

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.photo)
        if img.height > 250 or img.width > 250:
            output_size = (250, 250)
            img.thumbnail(output_size)
            img.save(self.photo.path)


class Tweet(models.Model):
    author            = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    tweet_content     = models.TextField()
    creation_datetime = models.DateTimeField(auto_now_add=True)
    update_datetime   = models.DateTimeField(auto_now=True)
    is_blocked        = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('tweet-details', kwargs={'pk': self.pk})

    def __str__(self):
        return f'Tweet {self.pk} by {self.author} on {self.update_datetime.strftime("%Y/%m/%d %H:%M:%S")}'


class Comment(models.Model):
    author            = models.ForeignKey(get_user_model(), on_delete=models.SET(get_sentinel_user))
    tweet             = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    comment_content   = models.TextField()
    creation_datetime = models.DateTimeField(auto_now_add=True)
    is_blocked        = models.BooleanField(default=False)

    def __str__(self):
        return f'Comment {self.pk} on tweet {self.tweet_id} by {self.author} on {self.creation_datetime.strftime("%Y/%m/%d %H:%M:%S")}'


class Message(models.Model):
    from_user         = models.ForeignKey(get_user_model(), on_delete=models.SET(get_sentinel_user), related_name='messages_from_user')
    to_user           = models.ForeignKey(get_user_model(), on_delete=models.SET(get_sentinel_user), related_name='messages_to_user')
    message_content   = models.TextField()
    creation_datetime = models.DateTimeField(auto_now_add=True)
    is_read           = models.BooleanField(default=False)
    is_blocked        = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.from_user} -> {self.to_user} on {self.creation_datetime.strftime("%Y/%m/%d %H:%M:%S")}'

src/app_warbler/forms.py
#!/usr/bin/python3.7
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from . import models
from betterforms.multiform import MultiModelForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model  = User
        fields = ['username', 'email', 'password1', 'password2']


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model  = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model  = models.Profile
        fields = ['photo', 'about_myself']


class UserAndProfileUpdateForm(MultiModelForm):
    form_classes = {
        'user': UpdateUserForm,
        'profile': ProfileForm
    }


class TweetForm(forms.ModelForm):
    class Meta:
        model  = models.Tweet
        fields = '__all__'


class MessageForm(forms.ModelForm):
    class Meta:
        model  = models.Message
        fields = ['message_content']


class CommentForm(forms.ModelForm):
    class Meta:
        model  = models.Comment
        fields = ['comment_content']

src/app_warbler/views.py
from django.contrib.auth.models import User
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse_lazy
from django.shortcuts import (
    redirect,
    reverse
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.views import generic
from . import (
    models,
    forms
)


class CreateUserView(generic.CreateView):
    model         = User
    template_name = 'app_warbler/create_user.html'
    form_class    = forms.CreateUserForm
    success_url   = reverse_lazy('login')


class DeleteUserView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model         = User
    template_name = 'app_warbler/delete_user.html'
    success_url   = reverse_lazy('create-user-sign-in')

    def test_func(self):
        return self.request.user.pk == self.get_object().pk

    def handle_no_permission(self):
        messages.error(self.request, 'Only the owner of the following profile can delete it! Log in as one!')
        return redirect('profile-details', pk=self.get_object().pk)

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        rsp = super().delete(request, *args, **kwargs)
        messages.success(request, f'Profile {obj} has been successfully deleted.')
        return rsp


class UpdateUserAndProfileView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model         = User
    template_name = 'app_warbler/update_user_and_profile.html'
    form_class    = forms.UserAndProfileUpdateForm

    def get_queryset(self):
        return self.model.objects.filter(profile__is_blocked=False)

    def get_success_url(self):
        return reverse_lazy('profile-details', kwargs={'pk': self.get_object().profile.pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(instance={
            'user': self.object,
            'profile': self.object.profile
        })
        return kwargs

    def test_func(self):
        return self.get_object() == self.request.user


class ListAllTweetsView(LoginRequiredMixin, generic.ListView):
    model         = models.Tweet
    template_name = 'app_warbler/all_tweets.html'
    paginate_by   = 10
    ordering      = ['-update_datetime']

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_blocked=False)


class TweetDetailsView(LoginRequiredMixin, generic.DetailView):
    model         = models.Tweet
    template_name = 'app_warbler/tweet_details.html'
    form_class    = forms.CommentForm

    def get_success_url(self):
        return reverse('tweet-details', kwargs={'pk': self.kwargs.get('pk')})

    def get_context_data(self, **kwargs):
        ctx                 = super().get_context_data(**kwargs)
        ctx['comments']     = self.get_object().comment_set.all().order_by('creation_datetime')
        ctx['comment_form'] = self.form_class()
        return ctx

    def get_queryset(self):
        return self.model.objects.filter(pk=self.kwargs.get('pk'), is_blocked=False)

    def post(self, *args, **kwargs):
        form = self.form_class(self.request.POST)
        if form.is_valid():
            form.instance.author = self.request.user
            form.instance.tweet  = self.get_object()
            form.save()
            messages.success(self.request, 'Your comment has been successfully posted.')
        else:
            messages.error(self.request, 'We were unable to post your comment.')
        return redirect(self.get_success_url())


class CreateTweetView(LoginRequiredMixin, generic.CreateView):
    model         = models.Tweet
    template_name = 'app_warbler/create_tweet.html'
    fields        = ['tweet_content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdateTweetView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model         = models.Tweet
    template_name = 'app_warbler/update_tweet.html'
    fields        = ['tweet_content']

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_blocked=False)

    def test_func(self):
        return self.request.user.id == self.get_object().author.id

    def handle_no_permission(self):
        messages.error(self.request, 'Only the author of the following post can edit it! Log in as one!')
        return redirect('tweet-details', pk=self.get_object().pk)


class DeleteTweetView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model         = models.Tweet
    template_name = 'app_warbler/delete_tweet.html'

    def get_success_url(self):
        return reverse_lazy('profile-details', kwargs={'pk': self.get_object().author.id})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_blocked=False)

    def test_func(self):
        return self.request.user.id == self.get_object().author.id

    def handle_no_permission(self):
        messages.error(self.request, 'Only the author of the following post can delete it! Log in as one!')
        return redirect('tweet-details', pk=self.get_object().pk)


class ProfileDetailsView(LoginRequiredMixin, generic.DetailView):
    model         = models.Profile
    template_name = 'app_warbler/profile_details.html'

    def get_context_data(self, **kwargs):
        ctx           = super().get_context_data(**kwargs)
        ctx['tweets'] = self.object.user.tweet_set.all().order_by('-update_datetime')
        return ctx


class CreateMessageView(LoginRequiredMixin, generic.CreateView):
    model         = models.Message
    template_name = 'app_warbler/create_message.html'
    form_class    = forms.MessageForm
    pk_url_kwarg  = 'to_user'

    def get_context_data(self, **kwargs):
        ctx            = super().get_context_data(**kwargs)
        ctx['to_user'] = User.objects.get(pk=self.kwargs.get(self.pk_url_kwarg))
        return ctx

    def get_success_url(self):
        return reverse('user-messages', kwargs={'pk': self.request.user.pk})

    def form_valid(self, form):
        form.instance.from_user = self.request.user
        form.instance.to_user   = self.get_context_data()['to_user']
        rsp                     = super().form_valid(form)
        messages.success(self.request, f'Message to {form.instance.to_user} successfully sent.')
        return rsp


class ListUserMessagesView(LoginRequiredMixin, generic.ListView):
    model         = models.Message
    template_name = 'app_warbler/user_messages.html'
    paginate_by   = 10
    ordering      = ['-creation_datetime']

    def get_queryset(self):
        return super().get_queryset().filter(
            Q(is_blocked=False),
            Q(from_user=self.request.user) | Q(to_user=self.request.user)
        )


class MessageDetailsView(LoginRequiredMixin, generic.DetailView):
    model         = models.Message
    template_name = 'app_warbler/message_details.html'

    def get_queryset(self):
        return self.model.objects.filter(pk=self.kwargs.get('pk'), is_blocked=False)

    def get(self, request, *args, **kwargs):
        self.get_queryset().update(is_read=True)
        return super().get(self.request)


class DeleteCommentView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
        model         = models.Comment
        template_name = 'app_warbler/delete_comment.html'

        def get_success_url(self):
            return reverse_lazy('tweet-details', kwargs={'pk': self.get_object().tweet.id})

        def get_queryset(self):
            queryset = super().get_queryset()
            return queryset.filter(is_blocked=False)

        def test_func(self):
            return self.request.user.id == self.get_object().author.id

        def handle_no_permission(self):
            messages.error(self.request, 'Only the author of that comment can delete it! Log in as one!')
            return redirect('tweet-details', pk=self.get_object().tweet.pk)

src/app_warbler/templates/app_warbler/all_tweets.html
{% extends 'app_warbler/base.html' %}

{% block content %}

    <h3>All Tweets:</h3>

    {% for tweet in tweet_list %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ tweet.author.profile.photo.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    {% if tweet.author.profile.is_blocked %}
                        <span class="mr-2 text-muted">{{ tweet.author }} (user blocked)</span>
                    {% else %}
                        <a class="mr-2" href="{% url 'profile-details' tweet.author_id %}">{{ tweet.author }}</a>
                    {% endif %}
                        <small class="text-muted">Created: {{ tweet.creation_datetime|date:"Y/m/d H:i:s" }}</small>
                    {% if tweet.creation_datetime|date:"Y/m/d H:i:s" != tweet.update_datetime|date:"Y/m/d H:i:s" %}
                        <small class="text-muted">Updated: {{ tweet.update_datetime|date:"Y/m/d H:i:s" }}</small>
                    {% endif %}
                </div>
                <a class="article-content" href="{% url 'tweet-details' tweet.pk %}">{{ tweet.tweet_content }}</a>
            </div>
        </article>
    {% endfor %}

{% endblock content %}

src/app_warbler/templates/app_warbler/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="icon" href="{% static 'app_warbler/favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'app_warbler/css/app_warbler.css' %}">

    <!-- jQuery -->
    <script  src="https://code.jquery.com/jquery-3.3.1.js"  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="  crossorigin="anonymous"></script>

    <title>Warbler</title>
</head>
<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'list-all-tweets' %}">Warbler<span id="beta">beta</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'create-tweet' %}">Add new tweet</a>
                            <a class="nav-item nav-link" href="{% url 'user-messages' user.pk %}">Messages</a>
                        {% endif %}
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'profile-details' user.pk %}">{{ user }}</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'create-user-sign-in' %}">Sign up!</a>
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                {% block content %}
                {% endblock content%}

            </div>
        </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

src/app_warbler/templates/app_warbler/create_message.html
{% extends 'app_warbler/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <div>
        <h3>Sending message to user {{ to_user.username }}</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Send" class="btn btn-outline-info">
        </form>
    </div>
{% endblock content %}

src/app_warbler/templates/app_warbler/create_user.html
{% extends 'app_warbler/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <div>
        <h3>Create new account:</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Create" class="btn btn-outline-info">
        </form>
    </div>
{% endblock content %}

src/app_warbler/templates/app_warbler/delete_tweet.html
{% extends 'app_warbler/base.html' %}

{% block content %}

    <h2>Deleting {{ object }}</h2>
    <form method="post">
        {% csrf_token %}
        <h4>Do you really want to delete this tweet? There won't be possibility to undo that!</h4>
        <input class="btn btn-outline-danger" type="submit" value="Confirm">
        <a class="btn btn-outline-primary" href="{% url 'tweet-details' object.pk %}">Cancel</a>
    </form>

{% endblock content %}

src/app_warbler/templates/app_warbler/delete_user.html
{% extends 'app_warbler/base.html' %}

{% block content %}

    <h2>Deleting {{ object }}'s account</h2>
    <form method="post">
        {% csrf_token %}
        <h4>Do you really want to delete your account? There won't be possibility to undo that!</h4>
        <input class="btn btn-outline-danger" type="submit" value="Confirm">
        <a class="btn btn-outline-primary" href="{% url 'profile-details' object.pk %}">Cancel</a>
    </form>

{% endblock content %}

src/app_warbler/templates/app_warbler/logout.html
{% extends 'app_warbler/base.html' %}

{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

src/app_warbler/templates/app_warbler/message_details.html
{% extends 'app_warbler/base.html' %}

{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ message.from_user.profile.photo.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <h4 class="mr-2">Message {{ message.id }}:</h4>
                {% if message.from_user.is_blocked %}
                    <span class="mr-2 text-muted">{{ message.from_user }} (user blocked)</span>
                    <small class="text-muted">{{ message.creation_datetime|date:"Y/m/d H:i:s" }}</small>
                {% else %}
                    <p class="mr-2">
                        From:
                        <a class="mr-2" href="{% url 'profile-details' message.from_user.id %}">{{ message.from_user }}</a>
                        <small class="text-muted">{{ message.creation_datetime|date:"Y/m/d H:i:s" }}</small><br>
                        To:
                        <a class="mr-2" href="{% url 'profile-details' message.to_user.id %}">{{ message.to_user }}</a>
                        <small class="text-muted">{{ message.creation_datetime|date:"Y/m/d H:i:s" }}</small>
                    </p>
                {% endif %}
            </div>
            <p class="article-content">{{ message.message_content }}</p>
        </div>
    </article>

{% endblock content %}

src/app_warbler/templates/app_warbler/password_reset_complete.html
{% extends "app_warbler/base.html" %}

{% block content %}
    <div class="alert alert-info">
        Your password has been reset.
    </div>
    <a href="{% url 'login' %}">Log in</a>
{% endblock content %}

src/app_warbler/templates/app_warbler/password_reset_done.html
{% extends "app_warbler/base.html" %}

{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content %}

src/app_warbler/templates/app_warbler/profile_details.html
{% extends 'app_warbler/base.html' %}

{% block content %}

    <article class="media content-section">
        <div class="media-body">
            <h4>User {{ profile.user.username }} information:</h4>
            <a class="btn btn-outline-primary btn-sm" href="{% url 'create-message' profile.user_id %}">Send message to this user</a>
            <div>
                <img class="article-content img-profile" src="{{ profile.photo.url }}" alt="Here should be post's photo"><br>
                <small class="text-muted">{{ profile.user.email }}</small><br>
                {% if profile.user.first_name or profile.user.last_name %}
                    {{ profile.user.first_name }} {{ profile.user.last_name }}
                {% endif %}<br>
                {% if profile.about_myself %}
                    <p class="article-content">About myself: {{ profile.about_myself }}</p>
                {% endif %}
            </div>

            {% if profile.user == user %}
                <a class="btn btn-outline-info" href="{% url 'update-user' profile.pk %}">Update information about you</a>
                <a class="btn btn-outline-danger" href="{% url 'delete-user' profile.user.pk %}">Delete account</a>
            {% endif %}
        </div>
    </article>

    <h4>User's tweets:</h4>
    {% for tweet in tweets %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">Created: {{ tweet.creation_datetime|date:"Y/m/d H:i:s" }}</small>
                    {% if tweet.creation_datetime|date:"Y/m/d H:i:s" != tweet.update_datetime|date:"Y/m/d H:i:s" %}
                        <small class="text-muted">Updated: {{ tweet.update_datetime|date:"Y/m/d H:i:s" }}</small>
                    {% endif %}
                </div>
                <a class="article-content" href="{% url 'tweet-details' tweet.id %}">{{ tweet.tweet_content }}</a>
            </div>
        </article>
    {% endfor %}

{% endblock content %}

src/app_warbler/templates/app_warbler/tweet_details.html
{% extends 'app_warbler/base.html' %}
{% load crispy_forms_filters %}

{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ tweet.author.profile.photo.url }}">
        <div class="media-body">
            <div class="article-metadata">
                {% if tweet.author.profile.is_blocked %}
                    <span class="mr-2 text-muted">{{ tweet.author }} (user blocked)</span>
                {% else %}
                    <a class="mr-2" href="{% url 'profile-details' tweet.author_id %}">{{ tweet.author }}</a>
                {% endif %}
                    <small class="text-muted">Created: {{ tweet.creation_datetime|date:"Y/m/d H:i:s" }}</small>
                {% if tweet.creation_datetime|date:"Y/m/d H:i:s" != tweet.update_datetime|date:"Y/m/d H:i:s" %}
                    <small class="text-muted">Updated: {{ tweet.update_datetime|date:"Y/m/d H:i:s" }}</small>
                {% endif %}
            </div>
            <p class="article-content">{{ tweet.tweet_content }}</p>

            {% if tweet.author == user %}
                <a class="btn btn-outline-info" href="{% url 'update-tweet' tweet.pk %}">Update tweet</a>
                <a class="btn btn-outline-danger" href="{% url 'delete-tweet' tweet.pk %}">Delete tweet</a>
            {% endif %}
        </div>
    </article>

    <h4 class="article-title">Comments:</h4>
    {% for comment in comments %}
        <fieldset class="col-md-6">
            <div class="panel panel-default content-section">
                <div class="article-metadata">
                    {% if comment.author.profile.is_blocked %}
                        <span class="mr-2 text-muted">{{ comment.author }} (user blocked)</span>
                    {% elif comment.author.username == 'Deleted_user' %}
                        <span class="mr-2 text-muted">deleted user</span>
                    {% else %}
                        <a class="mr-2" href="{% url 'profile-details' comment.author_id %}">{{ comment.author }}</a>
                    {% endif %}
                        <small class="text-muted">{{ comment.creation_datetime|date:"Y/m/d H:i:s" }}</small>
                </div>
                <p>{{ comment.comment_content }}</p>
                {% if comment.author == user %}
                    <a class="btn btn-outline-danger" href="{% url 'delete-comment' comment.pk %}">Delete comment</a>
                {% endif %}
            </div>
        </fieldset>
    {% endfor %}

    <h4>Add comment:</h4>
    <form method="post">
        {% csrf_token %}
            {{ comment_form|crispy }}
        <input type="submit" value="Post comment" class="btn btn-outline-info">
    </form>

{% endblock content %}

src/app_warbler/templates/app_warbler/update_tweet.html
{% extends 'app_warbler/base.html' %}
{% load crispy_forms_filters %}

{% block content %}

    <h4>Update Tweet:</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Save changes" class="btn btn-outline-info">
        <a class="btn btn-outline-primary" href="{% url 'tweet-details' object.pk %}">Cancel</a>
    </form>

{% endblock content %}

src/app_warbler/templates/app_warbler/user_messages.html
{% extends 'app_warbler/base.html' %}
{% load static %}

{% block content %}

    <h4>User {{ user.username }} messages:</h4>

    {% for msg in message_list %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ msg.from_user.profile.photo.url }}">
            <div class="media-body">
                <div class="article-metadata d-flex">
                    <span>from: </span>
                    {% if msg.from_user.profile.is_blocked %}
                        <span class="mr-2 text-muted">{{ msg.from_user }} (user blocked)</span>
                    {% else %}
                        <a class="mr-2" href="{% url 'profile-details' msg.from_user_id %}">{{ msg.from_user }}</a>
                    {% endif %}
                        <small class="mr-2 text-muted">Created: {{ msg.creation_datetime|date:"Y/m/d H:i:s" }}</small>
                    <span class="ml-auto">to: </span>
                    {% if msg.to_user.profile.is_blocked %}
                        <span class="mr-2 text-muted">{{ msg.to_user }} (user blocked)</span>
                    {% else %}
                        <a class="mr-2" href="{% url 'profile-details' msg.to_user_id %}">{{ msg.to_user }}</a>
                    {% endif %}
                </div>
                <a class="article-content {% if not msg.is_read %}unread-message{% endif %}" href="{% url 'msg-details' msg.pk %}">{{ msg.message_content|slice:":10" }}...</a>
            </div>
            <img class="rounded-circle article-img" src="{{ msg.to_user.profile.photo.url }}">
        </article>
    {% endfor %}

{% endblock content %}